Initial touch up (fixed ver)
CodeTheDev/Airship pull request #3
Opened 2022-08-16 22:02 UTC by kirancrooks

2022-08-17 21:30 UTC, CodeTheDev requested changes

2022-08-17 21:30 UTC, CodeTheDev commented on dashboard/src/splash.html
> +          <a href="https://wilbursootlive.notion.site/Wilbur-Soot-Discord-Privacy-Policy-f6d87ba5c3034cc6b820d6a64af212fa">Privacy Policy</a>
I'd prefer if this was left as is instead of redirecting to the Wilbur privacy policy.

2022-08-17 21:30 UTC, CodeTheDev commented on dashboard/src/index.html
> +    <title>Airship - A Zeppelin Fork</title>
I'd also prefer if this was left as is. I'm thinking of a funny slogan to add.

2022-08-18 20:20 UTC, kirancrooks commented on dashboard/src/index.html
> +    <title>Airship - A Zeppelin Fork</title>
Reverted 👍

2022-08-18 20:20 UTC, kirancrooks commented on dashboard/src/splash.html
> +          <a href="https://wilbursootlive.notion.site/Wilbur-Soot-Discord-Privacy-Policy-f6d87ba5c3034cc6b820d6a64af212fa">Privacy Policy</a>
Reverted 👍

2022-08-18 20:20 UTC, kirancrooks commented
Check the PR again

2022-08-18 20:25 UTC, CodeTheDev approved these changes
LGTM

2022-08-18 20:28 UTC, merged